### ISSUE TITLE
ldc2 build under Windows - dependency libraries are not specified properly

### ISSUE THREAD

**Issue by buggins** [D-Programming-Language/dub#731]
tetris ~master: building configuration "application"...
C:\Tools\D\ldc2-0.16.1-win64-msvc\bin\ldc2.exe -of.dub\build\application-debug-windows-x86-ldc_0-5EAB8258AE7EB94DF86F1E8E65AB6EB3\tetris.exe -
d-debug -g -w -oq -od=.dub/obj -d-version=USE_OPENGL -d-version=EmbedStandardResources -d-version=USE_FREETYPE -d-version=ForceLogs -d-version
=Unicode -d-version=Have_tetris -d-version=Have_dlangui -d-version=Have_derelict_ft -d-version=Have_derelict_util -d-version=Have_derelict_gl3
 -d-version=Have_derelict_sdl2 -d-version=Have_dlib -d-version=Have_gl3n -Isrc -IC:\Users\vlopatin\AppData\Roaming\dub\packages\dlangui-master
\3rdparty 
...
 src\gui.d src\model.d src\tetris.d C:\Users\vlopatin\AppDat
a\Roaming\dub\packages\dlangui-master\\src\win_app.def C:\Users\vlopatin\AppData\Roaming\dub\packages\dlangui-master\lib\libdlangui.a C:\Users
\vlopatin\AppData\Roaming\dub\packages\derelict-ft-1.0.2\lib\libDerelictFT.a C:\Users\vlopatin\AppData\Roaming\dub\packages\derelict-gl3-1.0.1
7\lib\libDerelictGL3.a C:\Users\vlopatin\AppData\Roaming\dub\packages\derelict-sdl2-1.9.7\lib\libDerelictSDL2.a C:\Users\vlopatin\AppData\Roam
ing\dub\packages\derelict-util-2.0.4\lib\libDerelictUtil.a C:\Users\vlopatin\AppData\Roaming\dub\packages\dlib-0.7.1\libdlib.a C:\Users\vlopat
in\AppData\Roaming\dub\packages\gl3n-1.2.0\libgl3n.a
Error: unrecognized file extension a

Reproduces on both latest available download DUB version and ~master.

**Comment by marcioapm** [comment]
This happens with LDC2 0.17.0 alpha1 as well.

Can't use LDC with dub on Windows at the moment :(

**Comment by inDream** [comment]
Is it fixed in #618 ? Can anyone confirm about it?

**Comment by buggins** [comment]
Still reproduced on ~master version of DUB and ldc2-0.17.0 alpha
Error: unrecognized file extension a
C:\Tools\D\ldc2-0.17.0-alpha1-win64-msvc\bin\ldc2.exe failed with exit code 1.

**Comment by chalucha** [comment]
Can confirm this with latest ~master and ldc2-0.17.0

**Comment by wilzbach** [comment]
Is this issue still present? Can it be closed? Is there a simple way to reproduce it?
